DROP DATABASE IF EXISTS news;
CREATE DATABASE news;
USE news;

CREATE TABLE `users` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`email` TEXT NOT NULL,
	`name` TEXT NOT NULL,
	`url_avatar` TEXT,
	PRIMARY KEY (`id`)
);

CREATE TABLE `news_save` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`idUser` INT NOT NULL,
	`title` TEXT NOT NULL,
	`link` TEXT NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `posts` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`idUser` INT NOT NULL,
	`idTopic` INT NOT NULL,
	`content` TEXT NOT NULL,
	`url_image` TEXT,
	`created_at` DATETIME NOT NULL DEFAULT NOW(),
	`last_update` DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY (`id`)
);

CREATE TABLE `topics` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`topic` TEXT NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `votes` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`idPost` INT NOT NULL,
	`idUser` INT NOT NULL,
	`status` INT(2) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `comments` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`idPost` INT NOT NULL,
	`idUser` INT NOT NULL,
	`content` TEXT NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY (`id`)
);

ALTER TABLE `news_save` ADD CONSTRAINT `news_save_fk0` FOREIGN KEY (`idUser`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `posts` ADD CONSTRAINT `posts_fk0` FOREIGN KEY (`idUser`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `posts` ADD CONSTRAINT `posts_fk1` FOREIGN KEY (`idTopic`) REFERENCES `topics`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `votes` ADD CONSTRAINT `votes_fk0` FOREIGN KEY (`idPost`) REFERENCES `posts`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `votes` ADD CONSTRAINT `votes_fk1` FOREIGN KEY (`idUser`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `comments` ADD CONSTRAINT `comments_fk0` FOREIGN KEY (`idPost`) REFERENCES `posts`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `comments` ADD CONSTRAINT `comments_fk1` FOREIGN KEY (`idUser`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
